# Most config values are set via CLI arguments. This file can be used to
# overwrite all CLI arguments and to set additional parameters.

###########################
# CLI argument overwrites #
###########################

# gitlab_url: "https://gitlab.com"
# group_id: 42
# access_token: "0x123456789ABCDEF"
# output_dir: "out"
# create_subdir: False

#######################################
# Additional configuration parameters #
#######################################

# Log-level from logging package (e.g. logging.DEBUG, logging.INFO, logging.ERROR)
loglevel: "INFO"

# Group backup creation delay in seconds. Unlike the Project Export API, GitLab does not provide an export_status for
# Group Exports. It is up to the user to ensure the export is finished. However, Group Exports only contain metadata,
# so they are much faster than Project Exports.
group_backup_backoff_sec: 5

# Number of retries when the export of an object (e.g. repository) failed.
# If the maximum number of retries is reached, the script exists with an error.
export_retry_count: 3
